export const FETCH_SPOTS = "FETCH_SPOTS";
export const UPDATE_START_AT = "UPDATE_START_AT";
export const FILTER_SPOTS = "FILTER_SPOTS";
export const REGISTER_MEMBER = "REGISTER_MEMBER";
export const SHOW_SIGN_IN = "SHOW_SIGN_IN";